language: node_js
node_js:
- 11
- 8
script:
- npm run all
- npm run validate

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: kos-registry.json
  skip_cleanup: true
  on:
    tags: true
